<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tei="http://www.tei-c.org/ns/1.0"
    exclude-result-prefixes="xs tei"
    version="2.0">
 
 <!-- This exports the .xml type -->
    <xsl:output method="xml" encoding="utf-8" indent="yes"/>
     <xsl:strip-space elements="*"/>

    <xsl:template match="/">
        <xsl:apply-templates/>
    </xsl:template>
    
    <!-- This replaces the default teiHeader with the Heresies Project teiHeader -->
    <xsl:template match="tei:teiHeader">
        <teiHeader xmlns="http://www.tei-c.org/ns/1.0">
            <fileDesc>
                <titleStmt>
                    <title>The Heresies Project</title>
                </titleStmt>
                <publicationStmt>
                    <p>A Bucknell Production</p>
                </publicationStmt>
                <sourceDesc>
                    <p>Information about the source</p>
                </sourceDesc>
            </fileDesc>
        </teiHeader>
        <xsl:apply-templates/>
    </xsl:template>

<!-- This removes the duplicated fileDesc structure (which is now managed by the above -->
        <xsl:template match="tei:fileDesc"/>
 
<!-- This strips out the lb tags that are auto-generated by Transkribus -->
    <xsl:template match="tei:lb"/>
    
    

    
   <xsl:template match="@* | node()">
        <xsl:copy>
            <xsl:apply-templates select="@* | node()"/>
        </xsl:copy>
    </xsl:template>

    
</xsl:stylesheet>